/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se_makeup;

/**
 *
 * @author Hammad
 */
public class Code extends javax.swing.JFrame {

    /**
     * Creates new form Code
     */
    public Code() {
        initComponents();
        languageCB.removeAllItems();
        languageCB.addItem("C");
        languageCB.addItem("C++");
        languageCB.addItem("Python");
        languageCB.addItem("SQL");
        languageCB.addItem("R");
        languageCB.addItem("Java");
        languageCB.addItem("Matlab");
        languageCB.addItem("HTML");
        languageCB.addItem("XML");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languageCB = new javax.swing.JComboBox<>();
        languageJL = new javax.swing.JLabel();
        captionJL = new javax.swing.JLabel();
        captionTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        codeTF = new javax.swing.JTextArea();
        codeJL = new javax.swing.JLabel();
        addcodeB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        languageCB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        languageCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        languageJL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        languageJL.setText("Language");

        captionJL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        captionJL.setText("Caption");

        captionTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        captionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captionTFActionPerformed(evt);
            }
        });

        codeTF.setColumns(20);
        codeTF.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        codeTF.setRows(5);
        jScrollPane1.setViewportView(codeTF);

        codeJL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        codeJL.setText("Code");

        addcodeB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addcodeB.setText("Add Code");
        addcodeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcodeBActionPerformed(evt);
            }
        });

        cancelB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(cancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addcodeB, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(languageJL)
                            .addComponent(captionJL)
                            .addComponent(codeJL))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(captionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(languageCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageJL))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(captionJL)
                    .addComponent(captionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeJL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcodeB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void captionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_captionTFActionPerformed

    private void addcodeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcodeBActionPerformed
        // TODO add your handling code here:
        String language = String.valueOf(languageCB.getSelectedItem());
        String caption = captionTF.getText();
        String code = codeTF.getText();
        TextToLatex ttl = new TextToLatex();
        ttl.appendToLatex(ttl.codeToTex(language, caption, code));
        setVisible(false);
        Body bd = new Body();
        bd.setVisible(true);
        
        
    }//GEN-LAST:event_addcodeBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Body bod = new Body();
        bod.setVisible(true);
    }//GEN-LAST:event_cancelBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Code().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcodeB;
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel captionJL;
    private javax.swing.JTextField captionTF;
    private javax.swing.JLabel codeJL;
    private javax.swing.JTextArea codeTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> languageCB;
    private javax.swing.JLabel languageJL;
    // End of variables declaration//GEN-END:variables
}
